#ifndef XM_CONFIG_H
#define XM_CONFIG_H

// version
#define XM_CONFIG_VERSION "2.9.9"
#define XM_CONFIG_VERSION_MAJOR 2
#define XM_CONFIG_VERSION_MINOR 9
#define XM_CONFIG_VERSION_ALTER 9
#define XM_CONFIG_VERSION_BUILD 20250520
#define XM_CONFIG_VERSION_BRANCH "HEAD"
#define XM_CONFIG_VERSION_COMMIT "40815a0"

#endif
