from cfn_resource_provider_schemas.Ssmcontacts.Contact import SCHEMA as Contact
from cfn_resource_provider_schemas.Ssmcontacts.Contactchannel import SCHEMA as Contactchannel
from cfn_resource_provider_schemas.Ssmcontacts.Plan import SCHEMA as Plan
from cfn_resource_provider_schemas.Ssmcontacts.Rotation import SCHEMA as Rotation
