from cfn_resource_provider_schemas.Sns.Subscription import SCHEMA as Subscription
from cfn_resource_provider_schemas.Sns.Topic import SCHEMA as Topic
from cfn_resource_provider_schemas.Sns.Topicinlinepolicy import SCHEMA as Topicinlinepolicy
from cfn_resource_provider_schemas.Sns.Topicpolicy import SCHEMA as Topicpolicy
