
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-05-21T10:54:54+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "2f274441952ed390b3e98ccb6e68ccd1fc1b5578",
 "version": "0.2.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
