# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from ...types.links import Links
from ...types.meta import Meta
from .files_delete_response_data import FilesDeleteResponseData


class FilesDeleteResponse(UncheckedBaseModel):
    data: typing.Optional[FilesDeleteResponseData] = pydantic.Field(default=None)
    """
    Contains a confirmation message
    """

    meta: typing.Optional[Meta] = None
    links: typing.Optional[Links] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
