from cfn_resource_provider_schemas.Kinesisanalyticsv2.Application import SCHEMA as Application
from cfn_resource_provider_schemas.Kinesisanalyticsv2.Applicationcloudwatchloggingoption import SCHEMA as Applicationcloudwatchloggingoption
from cfn_resource_provider_schemas.Kinesisanalyticsv2.Applicationoutput import SCHEMA as Applicationoutput
from cfn_resource_provider_schemas.Kinesisanalyticsv2.Applicationreferencedatasource import SCHEMA as Applicationreferencedatasource
