# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class CustomerExtraUpdateParams(UniversalBaseModel):
    """
    Parameters for updating a customer's extra metadata.
    """

    add: typing.Optional[typing.Dict[str, typing.Optional[str]]] = pydantic.Field(
        default=None
    )
    """
    Key-value pairs (`str: str`) to describe the customer
    """

    remove: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Extra Metadata keys to remove
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
