CONF_MODE_JSON = "JSON"  # We only handle JSON from the api
CONF_MODE_XML = "CSV"
CONF_MODE_CSV = "XML"

CONF_AVERAGING_NEWEST = 0
CONF_AVERAGING_QUARTERLY = 1
CONF_AVERAGING_HOURLY = 2

CONF_WIND_SPEED_UNIT_KNOTS = "knots"
CONF_WIND_SPEED_UNIT_KMH = "km/h"
CONF_WIND_SPEED_UNIT_MS = "m/s"
CONF_WIND_SPEED_UNIT_MPH = "mph"

CONF_TEMPERATURE_UNIT_CELSIUS = "Celsius"
CONF_TEMPERATURE_UNIT_FAHRENHEIT = "Fahrenheit"

CONF_OPTION_BATT = "batt"
CONF_OPTION_DAILY = "daily"

STATIONS_ALL = "all"
