# Generated by Django 4.2.4 on 2023-08-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lesrooster", "0008_one_default_time_grid"),
    ]

    operations = [
        migrations.CreateModel(
            name="LesroosterGlobalPermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("view_lesson_raster", "Can view lesson raster"),
                    ("view_timetable_creation", "Can view timetable creation"),
                ),
                "managed": False,
            },
        ),
    ]
