# coding: utf-8

"""
    Codex API

    List of endpoints and interfaces available to Codex API users

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from codex_api_client.models.manifest_item import ManifestItem

class TestManifestItem(unittest.TestCase):
    """ManifestItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManifestItem:
        """Test ManifestItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManifestItem`
        """
        model = ManifestItem()
        if include_optional:
            return ManifestItem(
                tree_cid = 'QmYyQSo1c1Ym7orWxLYvCrM2EmxFTANf8wXmmE7DWjhx5N',
                dataset_size = 56,
                block_size = 56,
                protected = True,
                filename = 'codex.png',
                mimetype = 'image/png',
                uploaded_at = 1729244192
            )
        else:
            return ManifestItem(
        )
        """

    def testManifestItem(self):
        """Test ManifestItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
