
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-05-20T23:54:34+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "df12f4c9fbbe7fc9840f3e3e0502c7dd35be9405",
 "version": "0.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
