# Generated by Django 5.0.1 on 2024-10-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placespage',
            name='seo_description_template',
            field=models.TextField(blank=True, help_text='SEO Description Template, Django template syntax is allowed.', max_length=1000, null=True),
        ),
    ]
