# Generated by Django 4.2.8 on 2025-05-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_placespage_seo_description_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='placespage',
            name='seo_priority',
            field=models.PositiveSmallIntegerField(default=100, help_text='SEO Priority, the higher the number, the higher the priority. (0-100)\nIf you want to use the default priority, set it to 0.\n100 is the highest priority and is translated to 1.0 in the sitemap.xml.\n0 is the lowest priority and is translated to 0.1 in the sitemap.xml.'),
        ),
        migrations.AddField(
            model_name='placespage',
            name='seo_priority_places',
            field=models.PositiveSmallIntegerField(default=100, help_text='SEO Priority for Places, the higher the number, the higher the priority. (0-100)\nIf you want to use the default priority, set it to 0.\n100 is the highest priority and is translated to 1.0 in the sitemap.xml.\n0 is the lowest priority and is translated to 0.1 in the sitemap.xml.'),
        ),
    ]
