# Generated by Django 4.2.8 on 2025-05-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_placespage_seo_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time the place was last updated.', verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='placespage',
            name='seo_change_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily'), ('none', 'None'), ('auto', 'Auto Calculate')], default='none', help_text="SEO Change Frequency, this tells search engines how often the page is updated.\nIf you want to exclude the change frequency, set it to 'None'.", max_length=10),
        ),
    ]
