# This file was auto-generated by Fern from our API Definition.

from .....core.pydantic_utilities import UniversalBaseModel
import typing
from .discover_port_details import DiscoverPortDetails
from .....core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class DiscoverSocketDetails(UniversalBaseModel):
    host: str
    ip: str
    ports: typing.Optional[typing.List[DiscoverPortDetails]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            extra = pydantic.Extra.allow
