from cfn_resource_provider_schemas.Kinesisanalytics.Application import SCHEMA as Application
from cfn_resource_provider_schemas.Kinesisanalytics.Applicationoutput import SCHEMA as Applicationoutput
from cfn_resource_provider_schemas.Kinesisanalytics.Applicationreferencedatasource import SCHEMA as Applicationreferencedatasource
