from cfn_resource_provider_schemas.Resourceexplorer2.Defaultviewassociation import SCHEMA as Defaultviewassociation
from cfn_resource_provider_schemas.Resourceexplorer2.Index import SCHEMA as Index
from cfn_resource_provider_schemas.Resourceexplorer2.View import SCHEMA as View
