VERSION = "0.2.4"
NAME = "mqtt-presence"
DESCRIPTION = "Lightweight MQTT-based presence detection with shutdown support"
REPOSITORY = "https://github.com/bjoernboeckle/mqtt-presence"
DOCUMENTATION = "https://github.com/bjoernboeckle/mqtt-presence/wiki"
AUTHORS = "['Bjoern Boeckle <bjoern@boeckle-net.de>']"
