# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .links_list import LinksListParams
from .meta_list import MetaListParams
from .task import TaskParams


class TaskListResponseParams(typing_extensions.TypedDict):
    meta: typing_extensions.NotRequired[MetaListParams]
    data: typing_extensions.NotRequired[typing.Sequence[TaskParams]]
    links: typing_extensions.NotRequired[LinksListParams]
