# -*- coding: utf-8 -*-
# Generated by https://github.com/i2y/connecpy/protoc-gen-connecpy.  DO NOT EDIT!
# source: mtmai/mtmpb/mtm.proto

from typing import Any, Protocol, Union

import httpx

from connecpy.async_client import AsyncConnecpyClient
from connecpy.base import Endpoint
from connecpy.server import ConnecpyServer
from connecpy.client import ConnecpyClient
from connecpy.context import ClientContext, ServiceContext

import mtmai.mtmpb.mtm_pb2 as _pb2

from google.protobuf import symbol_database

_sym_db = symbol_database.Default()


class MtmService(Protocol):
    async def Oauth2LoginHook(self, req: _pb2.Oauth2LoginHookRequest, ctx: ServiceContext) -> _pb2.AuthToken: ...
    async def Login(self, req: _pb2.LoginReq, ctx: ServiceContext) -> _pb2.LoginReply: ...
    async def Register(self, req: _pb2.RegisterReq, ctx: ServiceContext) -> _pb2.RegisterReply: ...
    async def GetMeta(self, req: _pb2.GetMetaReq, ctx: ServiceContext) -> _pb2.GetMetaRes: ...
    async def PullLogs(self, req: _pb2.PullLogReq, ctx: ServiceContext) -> _pb2.PullLogRes: ...
    async def MtmServerList(self, req: _pb2.MtmServerListReq, ctx: ServiceContext) -> _pb2.MtmServerListRes: ...
    async def ServiceMeta(self, req: _pb2.ServiceMetaReq, ctx: ServiceContext) -> _pb2.ServiceMetaRes: ...
    async def SlugPage(self, req: _pb2.SlugReq, ctx: ServiceContext) -> _pb2.SlugRes: ...
    async def Userinfo(self, req: _pb2.Empty, ctx: ServiceContext) -> _pb2.UserinfoRes: ...
    async def BlogPostGet(self, req: _pb2.BlogPostGetReq, ctx: ServiceContext) -> _pb2.BlogPost: ...
    async def BlogPostCreate(self, req: _pb2.BlogPostCreateReq, ctx: ServiceContext) -> _pb2.Result: ...
    async def BlogPostUpdate(self, req: _pb2.BlogPostUpdateReq, ctx: ServiceContext) -> _pb2.Result: ...
    async def BlogPostDelete(self, req: _pb2.ResDeleteReq, ctx: ServiceContext) -> _pb2.Result: ...
    async def BlogPostImport(self, req: _pb2.BlogPostImportReq, ctx: ServiceContext) -> _pb2.BlogPost: ...
    async def BlogCategorieList(self, req: _pb2.BlogCategorieListReq, ctx: ServiceContext) -> _pb2.BlogCategorieListReply: ...
    async def BlogCategorieGet(self, req: _pb2.BlogCategorieGetReq, ctx: ServiceContext) -> _pb2.BlogCategorie: ...
    async def BlogCategorieCreate(self, req: _pb2.BlogCategorieCreateReq, ctx: ServiceContext) -> _pb2.BlogCategorieCreateReply: ...
    async def BlogCategorieUpdate(self, req: _pb2.BlogCategorieUpdateReq, ctx: ServiceContext) -> _pb2.BlogCategorieUpdateReqply: ...
    async def BlogCategorieDelete(self, req: _pb2.ResDeleteReq, ctx: ServiceContext) -> _pb2.Result: ...
    async def BlogClean(self, req: _pb2.BlogCleanReq, ctx: ServiceContext) -> _pb2.Result: ...
    async def SiteGet(self, req: _pb2.SiteGetReq, ctx: ServiceContext) -> _pb2.Site: ...
    async def SiteCreate(self, req: _pb2.SiteCreateReq, ctx: ServiceContext) -> _pb2.SiteCreateRes: ...
    async def SiteUpdate(self, req: _pb2.SiteUpdateReq, ctx: ServiceContext) -> _pb2.Result: ...
    async def SiteDelete(self, req: _pb2.ResDeleteReq, ctx: ServiceContext) -> _pb2.Result: ...
    async def SiteImport(self, req: _pb2.SiteImportReq, ctx: ServiceContext) -> _pb2.Result: ...
    async def SiteSetupCftunnel(self, req: _pb2.SiteSetupCftunnelReq, ctx: ServiceContext) -> _pb2.SiteSetupCftunnelReply: ...
    async def SiteHostList(self, req: _pb2.SiteHostListReq, ctx: ServiceContext) -> _pb2.SiteHostListReply: ...
    async def SiteHostGet(self, req: _pb2.SiteHostGetReq, ctx: ServiceContext) -> _pb2.SiteHost: ...
    async def SiteHostCreate(self, req: _pb2.SiteHostCreateReq, ctx: ServiceContext) -> _pb2.Result: ...
    async def SiteHostUpdate(self, req: _pb2.SiteHostUpdateReq, ctx: ServiceContext) -> _pb2.Result: ...
    async def SiteHostDelete(self, req: _pb2.ResDeleteReq, ctx: ServiceContext) -> _pb2.Result: ...
    async def FormGet(self, req: _pb2.FormGetReq, ctx: ServiceContext) -> _pb2.FormSchema: ...
    async def FormCreate(self, req: _pb2.FormCreateReq, ctx: ServiceContext) -> _pb2.FormSchema: ...
    async def ArtContentClassify(self, req: _pb2.ArtContentClassifyReq, ctx: ServiceContext) -> _pb2.ArtContentClassifyReply: ...
    async def ArtRewrite(self, req: _pb2.ArtRewriteReq, ctx: ServiceContext) -> _pb2.ArtRewriteReply: ...


class MtmServiceServer(ConnecpyServer):
    def __init__(self, *, service: MtmService, server_path_prefix=""):
        super().__init__()
        self._prefix = f"{server_path_prefix}/mtmai.mtmpb.MtmService"
        self._endpoints = {
            "Oauth2LoginHook": Endpoint[_pb2.Oauth2LoginHookRequest, _pb2.AuthToken](
                service_name="MtmService",
                name="Oauth2LoginHook",
                function=getattr(service, "Oauth2LoginHook"),
                input=_pb2.Oauth2LoginHookRequest,
                output=_pb2.AuthToken,
                allowed_methods=("POST",),
            ),
            "Login": Endpoint[_pb2.LoginReq, _pb2.LoginReply](
                service_name="MtmService",
                name="Login",
                function=getattr(service, "Login"),
                input=_pb2.LoginReq,
                output=_pb2.LoginReply,
                allowed_methods=("POST",),
            ),
            "Register": Endpoint[_pb2.RegisterReq, _pb2.RegisterReply](
                service_name="MtmService",
                name="Register",
                function=getattr(service, "Register"),
                input=_pb2.RegisterReq,
                output=_pb2.RegisterReply,
                allowed_methods=("POST",),
            ),
            "GetMeta": Endpoint[_pb2.GetMetaReq, _pb2.GetMetaRes](
                service_name="MtmService",
                name="GetMeta",
                function=getattr(service, "GetMeta"),
                input=_pb2.GetMetaReq,
                output=_pb2.GetMetaRes,
                allowed_methods=("POST",),
            ),
            "PullLogs": Endpoint[_pb2.PullLogReq, _pb2.PullLogRes](
                service_name="MtmService",
                name="PullLogs",
                function=getattr(service, "PullLogs"),
                input=_pb2.PullLogReq,
                output=_pb2.PullLogRes,
                allowed_methods=("POST",),
            ),
            "MtmServerList": Endpoint[_pb2.MtmServerListReq, _pb2.MtmServerListRes](
                service_name="MtmService",
                name="MtmServerList",
                function=getattr(service, "MtmServerList"),
                input=_pb2.MtmServerListReq,
                output=_pb2.MtmServerListRes,
                allowed_methods=("POST",),
            ),
            "ServiceMeta": Endpoint[_pb2.ServiceMetaReq, _pb2.ServiceMetaRes](
                service_name="MtmService",
                name="ServiceMeta",
                function=getattr(service, "ServiceMeta"),
                input=_pb2.ServiceMetaReq,
                output=_pb2.ServiceMetaRes,
                allowed_methods=("POST",),
            ),
            "SlugPage": Endpoint[_pb2.SlugReq, _pb2.SlugRes](
                service_name="MtmService",
                name="SlugPage",
                function=getattr(service, "SlugPage"),
                input=_pb2.SlugReq,
                output=_pb2.SlugRes,
                allowed_methods=("POST",),
            ),
            "Userinfo": Endpoint[_pb2.Empty, _pb2.UserinfoRes](
                service_name="MtmService",
                name="Userinfo",
                function=getattr(service, "Userinfo"),
                input=_pb2.Empty,
                output=_pb2.UserinfoRes,
                allowed_methods=("POST",),
            ),
            "BlogPostGet": Endpoint[_pb2.BlogPostGetReq, _pb2.BlogPost](
                service_name="MtmService",
                name="BlogPostGet",
                function=getattr(service, "BlogPostGet"),
                input=_pb2.BlogPostGetReq,
                output=_pb2.BlogPost,
                allowed_methods=("POST",),
            ),
            "BlogPostCreate": Endpoint[_pb2.BlogPostCreateReq, _pb2.Result](
                service_name="MtmService",
                name="BlogPostCreate",
                function=getattr(service, "BlogPostCreate"),
                input=_pb2.BlogPostCreateReq,
                output=_pb2.Result,
                allowed_methods=("POST",),
            ),
            "BlogPostUpdate": Endpoint[_pb2.BlogPostUpdateReq, _pb2.Result](
                service_name="MtmService",
                name="BlogPostUpdate",
                function=getattr(service, "BlogPostUpdate"),
                input=_pb2.BlogPostUpdateReq,
                output=_pb2.Result,
                allowed_methods=("POST",),
            ),
            "BlogPostDelete": Endpoint[_pb2.ResDeleteReq, _pb2.Result](
                service_name="MtmService",
                name="BlogPostDelete",
                function=getattr(service, "BlogPostDelete"),
                input=_pb2.ResDeleteReq,
                output=_pb2.Result,
                allowed_methods=("POST",),
            ),
            "BlogPostImport": Endpoint[_pb2.BlogPostImportReq, _pb2.BlogPost](
                service_name="MtmService",
                name="BlogPostImport",
                function=getattr(service, "BlogPostImport"),
                input=_pb2.BlogPostImportReq,
                output=_pb2.BlogPost,
                allowed_methods=("POST",),
            ),
            "BlogCategorieList": Endpoint[_pb2.BlogCategorieListReq, _pb2.BlogCategorieListReply](
                service_name="MtmService",
                name="BlogCategorieList",
                function=getattr(service, "BlogCategorieList"),
                input=_pb2.BlogCategorieListReq,
                output=_pb2.BlogCategorieListReply,
                allowed_methods=("POST",),
            ),
            "BlogCategorieGet": Endpoint[_pb2.BlogCategorieGetReq, _pb2.BlogCategorie](
                service_name="MtmService",
                name="BlogCategorieGet",
                function=getattr(service, "BlogCategorieGet"),
                input=_pb2.BlogCategorieGetReq,
                output=_pb2.BlogCategorie,
                allowed_methods=("POST",),
            ),
            "BlogCategorieCreate": Endpoint[_pb2.BlogCategorieCreateReq, _pb2.BlogCategorieCreateReply](
                service_name="MtmService",
                name="BlogCategorieCreate",
                function=getattr(service, "BlogCategorieCreate"),
                input=_pb2.BlogCategorieCreateReq,
                output=_pb2.BlogCategorieCreateReply,
                allowed_methods=("POST",),
            ),
            "BlogCategorieUpdate": Endpoint[_pb2.BlogCategorieUpdateReq, _pb2.BlogCategorieUpdateReqply](
                service_name="MtmService",
                name="BlogCategorieUpdate",
                function=getattr(service, "BlogCategorieUpdate"),
                input=_pb2.BlogCategorieUpdateReq,
                output=_pb2.BlogCategorieUpdateReqply,
                allowed_methods=("POST",),
            ),
            "BlogCategorieDelete": Endpoint[_pb2.ResDeleteReq, _pb2.Result](
                service_name="MtmService",
                name="BlogCategorieDelete",
                function=getattr(service, "BlogCategorieDelete"),
                input=_pb2.ResDeleteReq,
                output=_pb2.Result,
                allowed_methods=("POST",),
            ),
            "BlogClean": Endpoint[_pb2.BlogCleanReq, _pb2.Result](
                service_name="MtmService",
                name="BlogClean",
                function=getattr(service, "BlogClean"),
                input=_pb2.BlogCleanReq,
                output=_pb2.Result,
                allowed_methods=("POST",),
            ),
            "SiteGet": Endpoint[_pb2.SiteGetReq, _pb2.Site](
                service_name="MtmService",
                name="SiteGet",
                function=getattr(service, "SiteGet"),
                input=_pb2.SiteGetReq,
                output=_pb2.Site,
                allowed_methods=("POST",),
            ),
            "SiteCreate": Endpoint[_pb2.SiteCreateReq, _pb2.SiteCreateRes](
                service_name="MtmService",
                name="SiteCreate",
                function=getattr(service, "SiteCreate"),
                input=_pb2.SiteCreateReq,
                output=_pb2.SiteCreateRes,
                allowed_methods=("POST",),
            ),
            "SiteUpdate": Endpoint[_pb2.SiteUpdateReq, _pb2.Result](
                service_name="MtmService",
                name="SiteUpdate",
                function=getattr(service, "SiteUpdate"),
                input=_pb2.SiteUpdateReq,
                output=_pb2.Result,
                allowed_methods=("POST",),
            ),
            "SiteDelete": Endpoint[_pb2.ResDeleteReq, _pb2.Result](
                service_name="MtmService",
                name="SiteDelete",
                function=getattr(service, "SiteDelete"),
                input=_pb2.ResDeleteReq,
                output=_pb2.Result,
                allowed_methods=("POST",),
            ),
            "SiteImport": Endpoint[_pb2.SiteImportReq, _pb2.Result](
                service_name="MtmService",
                name="SiteImport",
                function=getattr(service, "SiteImport"),
                input=_pb2.SiteImportReq,
                output=_pb2.Result,
                allowed_methods=("POST",),
            ),
            "SiteSetupCftunnel": Endpoint[_pb2.SiteSetupCftunnelReq, _pb2.SiteSetupCftunnelReply](
                service_name="MtmService",
                name="SiteSetupCftunnel",
                function=getattr(service, "SiteSetupCftunnel"),
                input=_pb2.SiteSetupCftunnelReq,
                output=_pb2.SiteSetupCftunnelReply,
                allowed_methods=("POST",),
            ),
            "SiteHostList": Endpoint[_pb2.SiteHostListReq, _pb2.SiteHostListReply](
                service_name="MtmService",
                name="SiteHostList",
                function=getattr(service, "SiteHostList"),
                input=_pb2.SiteHostListReq,
                output=_pb2.SiteHostListReply,
                allowed_methods=("POST",),
            ),
            "SiteHostGet": Endpoint[_pb2.SiteHostGetReq, _pb2.SiteHost](
                service_name="MtmService",
                name="SiteHostGet",
                function=getattr(service, "SiteHostGet"),
                input=_pb2.SiteHostGetReq,
                output=_pb2.SiteHost,
                allowed_methods=("POST",),
            ),
            "SiteHostCreate": Endpoint[_pb2.SiteHostCreateReq, _pb2.Result](
                service_name="MtmService",
                name="SiteHostCreate",
                function=getattr(service, "SiteHostCreate"),
                input=_pb2.SiteHostCreateReq,
                output=_pb2.Result,
                allowed_methods=("POST",),
            ),
            "SiteHostUpdate": Endpoint[_pb2.SiteHostUpdateReq, _pb2.Result](
                service_name="MtmService",
                name="SiteHostUpdate",
                function=getattr(service, "SiteHostUpdate"),
                input=_pb2.SiteHostUpdateReq,
                output=_pb2.Result,
                allowed_methods=("POST",),
            ),
            "SiteHostDelete": Endpoint[_pb2.ResDeleteReq, _pb2.Result](
                service_name="MtmService",
                name="SiteHostDelete",
                function=getattr(service, "SiteHostDelete"),
                input=_pb2.ResDeleteReq,
                output=_pb2.Result,
                allowed_methods=("POST",),
            ),
            "FormGet": Endpoint[_pb2.FormGetReq, _pb2.FormSchema](
                service_name="MtmService",
                name="FormGet",
                function=getattr(service, "FormGet"),
                input=_pb2.FormGetReq,
                output=_pb2.FormSchema,
                allowed_methods=("POST",),
            ),
            "FormCreate": Endpoint[_pb2.FormCreateReq, _pb2.FormSchema](
                service_name="MtmService",
                name="FormCreate",
                function=getattr(service, "FormCreate"),
                input=_pb2.FormCreateReq,
                output=_pb2.FormSchema,
                allowed_methods=("POST",),
            ),
            "ArtContentClassify": Endpoint[_pb2.ArtContentClassifyReq, _pb2.ArtContentClassifyReply](
                service_name="MtmService",
                name="ArtContentClassify",
                function=getattr(service, "ArtContentClassify"),
                input=_pb2.ArtContentClassifyReq,
                output=_pb2.ArtContentClassifyReply,
                allowed_methods=("POST",),
            ),
            "ArtRewrite": Endpoint[_pb2.ArtRewriteReq, _pb2.ArtRewriteReply](
                service_name="MtmService",
                name="ArtRewrite",
                function=getattr(service, "ArtRewrite"),
                input=_pb2.ArtRewriteReq,
                output=_pb2.ArtRewriteReply,
                allowed_methods=("POST",),
            ),
        }

    def serviceName(self):
        return "mtmai.mtmpb.MtmService"


class MtmServiceSync(Protocol):
    def Oauth2LoginHook(self, req: _pb2.Oauth2LoginHookRequest, ctx: ServiceContext) -> _pb2.AuthToken: ...
    def Login(self, req: _pb2.LoginReq, ctx: ServiceContext) -> _pb2.LoginReply: ...
    def Register(self, req: _pb2.RegisterReq, ctx: ServiceContext) -> _pb2.RegisterReply: ...
    def GetMeta(self, req: _pb2.GetMetaReq, ctx: ServiceContext) -> _pb2.GetMetaRes: ...
    def PullLogs(self, req: _pb2.PullLogReq, ctx: ServiceContext) -> _pb2.PullLogRes: ...
    def MtmServerList(self, req: _pb2.MtmServerListReq, ctx: ServiceContext) -> _pb2.MtmServerListRes: ...
    def ServiceMeta(self, req: _pb2.ServiceMetaReq, ctx: ServiceContext) -> _pb2.ServiceMetaRes: ...
    def SlugPage(self, req: _pb2.SlugReq, ctx: ServiceContext) -> _pb2.SlugRes: ...
    def Userinfo(self, req: _pb2.Empty, ctx: ServiceContext) -> _pb2.UserinfoRes: ...
    def BlogPostGet(self, req: _pb2.BlogPostGetReq, ctx: ServiceContext) -> _pb2.BlogPost: ...
    def BlogPostCreate(self, req: _pb2.BlogPostCreateReq, ctx: ServiceContext) -> _pb2.Result: ...
    def BlogPostUpdate(self, req: _pb2.BlogPostUpdateReq, ctx: ServiceContext) -> _pb2.Result: ...
    def BlogPostDelete(self, req: _pb2.ResDeleteReq, ctx: ServiceContext) -> _pb2.Result: ...
    def BlogPostImport(self, req: _pb2.BlogPostImportReq, ctx: ServiceContext) -> _pb2.BlogPost: ...
    def BlogCategorieList(self, req: _pb2.BlogCategorieListReq, ctx: ServiceContext) -> _pb2.BlogCategorieListReply: ...
    def BlogCategorieGet(self, req: _pb2.BlogCategorieGetReq, ctx: ServiceContext) -> _pb2.BlogCategorie: ...
    def BlogCategorieCreate(self, req: _pb2.BlogCategorieCreateReq, ctx: ServiceContext) -> _pb2.BlogCategorieCreateReply: ...
    def BlogCategorieUpdate(self, req: _pb2.BlogCategorieUpdateReq, ctx: ServiceContext) -> _pb2.BlogCategorieUpdateReqply: ...
    def BlogCategorieDelete(self, req: _pb2.ResDeleteReq, ctx: ServiceContext) -> _pb2.Result: ...
    def BlogClean(self, req: _pb2.BlogCleanReq, ctx: ServiceContext) -> _pb2.Result: ...
    def SiteGet(self, req: _pb2.SiteGetReq, ctx: ServiceContext) -> _pb2.Site: ...
    def SiteCreate(self, req: _pb2.SiteCreateReq, ctx: ServiceContext) -> _pb2.SiteCreateRes: ...
    def SiteUpdate(self, req: _pb2.SiteUpdateReq, ctx: ServiceContext) -> _pb2.Result: ...
    def SiteDelete(self, req: _pb2.ResDeleteReq, ctx: ServiceContext) -> _pb2.Result: ...
    def SiteImport(self, req: _pb2.SiteImportReq, ctx: ServiceContext) -> _pb2.Result: ...
    def SiteSetupCftunnel(self, req: _pb2.SiteSetupCftunnelReq, ctx: ServiceContext) -> _pb2.SiteSetupCftunnelReply: ...
    def SiteHostList(self, req: _pb2.SiteHostListReq, ctx: ServiceContext) -> _pb2.SiteHostListReply: ...
    def SiteHostGet(self, req: _pb2.SiteHostGetReq, ctx: ServiceContext) -> _pb2.SiteHost: ...
    def SiteHostCreate(self, req: _pb2.SiteHostCreateReq, ctx: ServiceContext) -> _pb2.Result: ...
    def SiteHostUpdate(self, req: _pb2.SiteHostUpdateReq, ctx: ServiceContext) -> _pb2.Result: ...
    def SiteHostDelete(self, req: _pb2.ResDeleteReq, ctx: ServiceContext) -> _pb2.Result: ...
    def FormGet(self, req: _pb2.FormGetReq, ctx: ServiceContext) -> _pb2.FormSchema: ...
    def FormCreate(self, req: _pb2.FormCreateReq, ctx: ServiceContext) -> _pb2.FormSchema: ...
    def ArtContentClassify(self, req: _pb2.ArtContentClassifyReq, ctx: ServiceContext) -> _pb2.ArtContentClassifyReply: ...
    def ArtRewrite(self, req: _pb2.ArtRewriteReq, ctx: ServiceContext) -> _pb2.ArtRewriteReply: ...


class MtmServiceServerSync(ConnecpyServer):
    def __init__(self, *, service: MtmServiceSync, server_path_prefix=""):
        super().__init__()
        self._prefix = f"{server_path_prefix}/mtmai.mtmpb.MtmService"
        self._endpoints = {
            "Oauth2LoginHook": Endpoint[_pb2.Oauth2LoginHookRequest, _pb2.AuthToken](
                service_name="MtmService",
                name="Oauth2LoginHook",
                function=getattr(service, "Oauth2LoginHook"),
                input=_pb2.Oauth2LoginHookRequest,
                output=_pb2.AuthToken,
                allowed_methods=("POST",),
            ),
            "Login": Endpoint[_pb2.LoginReq, _pb2.LoginReply](
                service_name="MtmService",
                name="Login",
                function=getattr(service, "Login"),
                input=_pb2.LoginReq,
                output=_pb2.LoginReply,
                allowed_methods=("POST",),
            ),
            "Register": Endpoint[_pb2.RegisterReq, _pb2.RegisterReply](
                service_name="MtmService",
                name="Register",
                function=getattr(service, "Register"),
                input=_pb2.RegisterReq,
                output=_pb2.RegisterReply,
                allowed_methods=("POST",),
            ),
            "GetMeta": Endpoint[_pb2.GetMetaReq, _pb2.GetMetaRes](
                service_name="MtmService",
                name="GetMeta",
                function=getattr(service, "GetMeta"),
                input=_pb2.GetMetaReq,
                output=_pb2.GetMetaRes,
                allowed_methods=("POST",),
            ),
            "PullLogs": Endpoint[_pb2.PullLogReq, _pb2.PullLogRes](
                service_name="MtmService",
                name="PullLogs",
                function=getattr(service, "PullLogs"),
                input=_pb2.PullLogReq,
                output=_pb2.PullLogRes,
                allowed_methods=("POST",),
            ),
            "MtmServerList": Endpoint[_pb2.MtmServerListReq, _pb2.MtmServerListRes](
                service_name="MtmService",
                name="MtmServerList",
                function=getattr(service, "MtmServerList"),
                input=_pb2.MtmServerListReq,
                output=_pb2.MtmServerListRes,
                allowed_methods=("POST",),
            ),
            "ServiceMeta": Endpoint[_pb2.ServiceMetaReq, _pb2.ServiceMetaRes](
                service_name="MtmService",
                name="ServiceMeta",
                function=getattr(service, "ServiceMeta"),
                input=_pb2.ServiceMetaReq,
                output=_pb2.ServiceMetaRes,
                allowed_methods=("POST",),
            ),
            "SlugPage": Endpoint[_pb2.SlugReq, _pb2.SlugRes](
                service_name="MtmService",
                name="SlugPage",
                function=getattr(service, "SlugPage"),
                input=_pb2.SlugReq,
                output=_pb2.SlugRes,
                allowed_methods=("POST",),
            ),
            "Userinfo": Endpoint[_pb2.Empty, _pb2.UserinfoRes](
                service_name="MtmService",
                name="Userinfo",
                function=getattr(service, "Userinfo"),
                input=_pb2.Empty,
                output=_pb2.UserinfoRes,
                allowed_methods=("POST",),
            ),
            "BlogPostGet": Endpoint[_pb2.BlogPostGetReq, _pb2.BlogPost](
                service_name="MtmService",
                name="BlogPostGet",
                function=getattr(service, "BlogPostGet"),
                input=_pb2.BlogPostGetReq,
                output=_pb2.BlogPost,
                allowed_methods=("POST",),
            ),
            "BlogPostCreate": Endpoint[_pb2.BlogPostCreateReq, _pb2.Result](
                service_name="MtmService",
                name="BlogPostCreate",
                function=getattr(service, "BlogPostCreate"),
                input=_pb2.BlogPostCreateReq,
                output=_pb2.Result,
                allowed_methods=("POST",),
            ),
            "BlogPostUpdate": Endpoint[_pb2.BlogPostUpdateReq, _pb2.Result](
                service_name="MtmService",
                name="BlogPostUpdate",
                function=getattr(service, "BlogPostUpdate"),
                input=_pb2.BlogPostUpdateReq,
                output=_pb2.Result,
                allowed_methods=("POST",),
            ),
            "BlogPostDelete": Endpoint[_pb2.ResDeleteReq, _pb2.Result](
                service_name="MtmService",
                name="BlogPostDelete",
                function=getattr(service, "BlogPostDelete"),
                input=_pb2.ResDeleteReq,
                output=_pb2.Result,
                allowed_methods=("POST",),
            ),
            "BlogPostImport": Endpoint[_pb2.BlogPostImportReq, _pb2.BlogPost](
                service_name="MtmService",
                name="BlogPostImport",
                function=getattr(service, "BlogPostImport"),
                input=_pb2.BlogPostImportReq,
                output=_pb2.BlogPost,
                allowed_methods=("POST",),
            ),
            "BlogCategorieList": Endpoint[_pb2.BlogCategorieListReq, _pb2.BlogCategorieListReply](
                service_name="MtmService",
                name="BlogCategorieList",
                function=getattr(service, "BlogCategorieList"),
                input=_pb2.BlogCategorieListReq,
                output=_pb2.BlogCategorieListReply,
                allowed_methods=("POST",),
            ),
            "BlogCategorieGet": Endpoint[_pb2.BlogCategorieGetReq, _pb2.BlogCategorie](
                service_name="MtmService",
                name="BlogCategorieGet",
                function=getattr(service, "BlogCategorieGet"),
                input=_pb2.BlogCategorieGetReq,
                output=_pb2.BlogCategorie,
                allowed_methods=("POST",),
            ),
            "BlogCategorieCreate": Endpoint[_pb2.BlogCategorieCreateReq, _pb2.BlogCategorieCreateReply](
                service_name="MtmService",
                name="BlogCategorieCreate",
                function=getattr(service, "BlogCategorieCreate"),
                input=_pb2.BlogCategorieCreateReq,
                output=_pb2.BlogCategorieCreateReply,
                allowed_methods=("POST",),
            ),
            "BlogCategorieUpdate": Endpoint[_pb2.BlogCategorieUpdateReq, _pb2.BlogCategorieUpdateReqply](
                service_name="MtmService",
                name="BlogCategorieUpdate",
                function=getattr(service, "BlogCategorieUpdate"),
                input=_pb2.BlogCategorieUpdateReq,
                output=_pb2.BlogCategorieUpdateReqply,
                allowed_methods=("POST",),
            ),
            "BlogCategorieDelete": Endpoint[_pb2.ResDeleteReq, _pb2.Result](
                service_name="MtmService",
                name="BlogCategorieDelete",
                function=getattr(service, "BlogCategorieDelete"),
                input=_pb2.ResDeleteReq,
                output=_pb2.Result,
                allowed_methods=("POST",),
            ),
            "BlogClean": Endpoint[_pb2.BlogCleanReq, _pb2.Result](
                service_name="MtmService",
                name="BlogClean",
                function=getattr(service, "BlogClean"),
                input=_pb2.BlogCleanReq,
                output=_pb2.Result,
                allowed_methods=("POST",),
            ),
            "SiteGet": Endpoint[_pb2.SiteGetReq, _pb2.Site](
                service_name="MtmService",
                name="SiteGet",
                function=getattr(service, "SiteGet"),
                input=_pb2.SiteGetReq,
                output=_pb2.Site,
                allowed_methods=("POST",),
            ),
            "SiteCreate": Endpoint[_pb2.SiteCreateReq, _pb2.SiteCreateRes](
                service_name="MtmService",
                name="SiteCreate",
                function=getattr(service, "SiteCreate"),
                input=_pb2.SiteCreateReq,
                output=_pb2.SiteCreateRes,
                allowed_methods=("POST",),
            ),
            "SiteUpdate": Endpoint[_pb2.SiteUpdateReq, _pb2.Result](
                service_name="MtmService",
                name="SiteUpdate",
                function=getattr(service, "SiteUpdate"),
                input=_pb2.SiteUpdateReq,
                output=_pb2.Result,
                allowed_methods=("POST",),
            ),
            "SiteDelete": Endpoint[_pb2.ResDeleteReq, _pb2.Result](
                service_name="MtmService",
                name="SiteDelete",
                function=getattr(service, "SiteDelete"),
                input=_pb2.ResDeleteReq,
                output=_pb2.Result,
                allowed_methods=("POST",),
            ),
            "SiteImport": Endpoint[_pb2.SiteImportReq, _pb2.Result](
                service_name="MtmService",
                name="SiteImport",
                function=getattr(service, "SiteImport"),
                input=_pb2.SiteImportReq,
                output=_pb2.Result,
                allowed_methods=("POST",),
            ),
            "SiteSetupCftunnel": Endpoint[_pb2.SiteSetupCftunnelReq, _pb2.SiteSetupCftunnelReply](
                service_name="MtmService",
                name="SiteSetupCftunnel",
                function=getattr(service, "SiteSetupCftunnel"),
                input=_pb2.SiteSetupCftunnelReq,
                output=_pb2.SiteSetupCftunnelReply,
                allowed_methods=("POST",),
            ),
            "SiteHostList": Endpoint[_pb2.SiteHostListReq, _pb2.SiteHostListReply](
                service_name="MtmService",
                name="SiteHostList",
                function=getattr(service, "SiteHostList"),
                input=_pb2.SiteHostListReq,
                output=_pb2.SiteHostListReply,
                allowed_methods=("POST",),
            ),
            "SiteHostGet": Endpoint[_pb2.SiteHostGetReq, _pb2.SiteHost](
                service_name="MtmService",
                name="SiteHostGet",
                function=getattr(service, "SiteHostGet"),
                input=_pb2.SiteHostGetReq,
                output=_pb2.SiteHost,
                allowed_methods=("POST",),
            ),
            "SiteHostCreate": Endpoint[_pb2.SiteHostCreateReq, _pb2.Result](
                service_name="MtmService",
                name="SiteHostCreate",
                function=getattr(service, "SiteHostCreate"),
                input=_pb2.SiteHostCreateReq,
                output=_pb2.Result,
                allowed_methods=("POST",),
            ),
            "SiteHostUpdate": Endpoint[_pb2.SiteHostUpdateReq, _pb2.Result](
                service_name="MtmService",
                name="SiteHostUpdate",
                function=getattr(service, "SiteHostUpdate"),
                input=_pb2.SiteHostUpdateReq,
                output=_pb2.Result,
                allowed_methods=("POST",),
            ),
            "SiteHostDelete": Endpoint[_pb2.ResDeleteReq, _pb2.Result](
                service_name="MtmService",
                name="SiteHostDelete",
                function=getattr(service, "SiteHostDelete"),
                input=_pb2.ResDeleteReq,
                output=_pb2.Result,
                allowed_methods=("POST",),
            ),
            "FormGet": Endpoint[_pb2.FormGetReq, _pb2.FormSchema](
                service_name="MtmService",
                name="FormGet",
                function=getattr(service, "FormGet"),
                input=_pb2.FormGetReq,
                output=_pb2.FormSchema,
                allowed_methods=("POST",),
            ),
            "FormCreate": Endpoint[_pb2.FormCreateReq, _pb2.FormSchema](
                service_name="MtmService",
                name="FormCreate",
                function=getattr(service, "FormCreate"),
                input=_pb2.FormCreateReq,
                output=_pb2.FormSchema,
                allowed_methods=("POST",),
            ),
            "ArtContentClassify": Endpoint[_pb2.ArtContentClassifyReq, _pb2.ArtContentClassifyReply](
                service_name="MtmService",
                name="ArtContentClassify",
                function=getattr(service, "ArtContentClassify"),
                input=_pb2.ArtContentClassifyReq,
                output=_pb2.ArtContentClassifyReply,
                allowed_methods=("POST",),
            ),
            "ArtRewrite": Endpoint[_pb2.ArtRewriteReq, _pb2.ArtRewriteReply](
                service_name="MtmService",
                name="ArtRewrite",
                function=getattr(service, "ArtRewrite"),
                input=_pb2.ArtRewriteReq,
                output=_pb2.ArtRewriteReply,
                allowed_methods=("POST",),
            ),
        }

    def serviceName(self):
        return "mtmai.mtmpb.MtmService"


class MtmServiceClient(ConnecpyClient):
    def Oauth2LoginHook(
        self,
        *,
        request: _pb2.Oauth2LoginHookRequest,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.AuthToken:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/Oauth2LoginHook",
            ctx=ctx,
            request=request,
            response_obj=_pb2.AuthToken,
            method=method,
            **kwargs,
        )

    def Login(
        self,
        *,
        request: _pb2.LoginReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.LoginReply:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/Login",
            ctx=ctx,
            request=request,
            response_obj=_pb2.LoginReply,
            method=method,
            **kwargs,
        )

    def Register(
        self,
        *,
        request: _pb2.RegisterReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.RegisterReply:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/Register",
            ctx=ctx,
            request=request,
            response_obj=_pb2.RegisterReply,
            method=method,
            **kwargs,
        )

    def GetMeta(
        self,
        *,
        request: _pb2.GetMetaReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.GetMetaRes:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/GetMeta",
            ctx=ctx,
            request=request,
            response_obj=_pb2.GetMetaRes,
            method=method,
            **kwargs,
        )

    def PullLogs(
        self,
        *,
        request: _pb2.PullLogReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.PullLogRes:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/PullLogs",
            ctx=ctx,
            request=request,
            response_obj=_pb2.PullLogRes,
            method=method,
            **kwargs,
        )

    def MtmServerList(
        self,
        *,
        request: _pb2.MtmServerListReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.MtmServerListRes:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/MtmServerList",
            ctx=ctx,
            request=request,
            response_obj=_pb2.MtmServerListRes,
            method=method,
            **kwargs,
        )

    def ServiceMeta(
        self,
        *,
        request: _pb2.ServiceMetaReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.ServiceMetaRes:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/ServiceMeta",
            ctx=ctx,
            request=request,
            response_obj=_pb2.ServiceMetaRes,
            method=method,
            **kwargs,
        )

    def SlugPage(
        self,
        *,
        request: _pb2.SlugReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.SlugRes:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/SlugPage",
            ctx=ctx,
            request=request,
            response_obj=_pb2.SlugRes,
            method=method,
            **kwargs,
        )

    def Userinfo(
        self,
        *,
        request: _pb2.Empty,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.UserinfoRes:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/Userinfo",
            ctx=ctx,
            request=request,
            response_obj=_pb2.UserinfoRes,
            method=method,
            **kwargs,
        )

    def BlogPostGet(
        self,
        *,
        request: _pb2.BlogPostGetReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.BlogPost:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/BlogPostGet",
            ctx=ctx,
            request=request,
            response_obj=_pb2.BlogPost,
            method=method,
            **kwargs,
        )

    def BlogPostCreate(
        self,
        *,
        request: _pb2.BlogPostCreateReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.Result:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/BlogPostCreate",
            ctx=ctx,
            request=request,
            response_obj=_pb2.Result,
            method=method,
            **kwargs,
        )

    def BlogPostUpdate(
        self,
        *,
        request: _pb2.BlogPostUpdateReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.Result:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/BlogPostUpdate",
            ctx=ctx,
            request=request,
            response_obj=_pb2.Result,
            method=method,
            **kwargs,
        )

    def BlogPostDelete(
        self,
        *,
        request: _pb2.ResDeleteReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.Result:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/BlogPostDelete",
            ctx=ctx,
            request=request,
            response_obj=_pb2.Result,
            method=method,
            **kwargs,
        )

    def BlogPostImport(
        self,
        *,
        request: _pb2.BlogPostImportReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.BlogPost:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/BlogPostImport",
            ctx=ctx,
            request=request,
            response_obj=_pb2.BlogPost,
            method=method,
            **kwargs,
        )

    def BlogCategorieList(
        self,
        *,
        request: _pb2.BlogCategorieListReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.BlogCategorieListReply:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/BlogCategorieList",
            ctx=ctx,
            request=request,
            response_obj=_pb2.BlogCategorieListReply,
            method=method,
            **kwargs,
        )

    def BlogCategorieGet(
        self,
        *,
        request: _pb2.BlogCategorieGetReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.BlogCategorie:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/BlogCategorieGet",
            ctx=ctx,
            request=request,
            response_obj=_pb2.BlogCategorie,
            method=method,
            **kwargs,
        )

    def BlogCategorieCreate(
        self,
        *,
        request: _pb2.BlogCategorieCreateReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.BlogCategorieCreateReply:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/BlogCategorieCreate",
            ctx=ctx,
            request=request,
            response_obj=_pb2.BlogCategorieCreateReply,
            method=method,
            **kwargs,
        )

    def BlogCategorieUpdate(
        self,
        *,
        request: _pb2.BlogCategorieUpdateReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.BlogCategorieUpdateReqply:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/BlogCategorieUpdate",
            ctx=ctx,
            request=request,
            response_obj=_pb2.BlogCategorieUpdateReqply,
            method=method,
            **kwargs,
        )

    def BlogCategorieDelete(
        self,
        *,
        request: _pb2.ResDeleteReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.Result:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/BlogCategorieDelete",
            ctx=ctx,
            request=request,
            response_obj=_pb2.Result,
            method=method,
            **kwargs,
        )

    def BlogClean(
        self,
        *,
        request: _pb2.BlogCleanReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.Result:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/BlogClean",
            ctx=ctx,
            request=request,
            response_obj=_pb2.Result,
            method=method,
            **kwargs,
        )

    def SiteGet(
        self,
        *,
        request: _pb2.SiteGetReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.Site:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/SiteGet",
            ctx=ctx,
            request=request,
            response_obj=_pb2.Site,
            method=method,
            **kwargs,
        )

    def SiteCreate(
        self,
        *,
        request: _pb2.SiteCreateReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.SiteCreateRes:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/SiteCreate",
            ctx=ctx,
            request=request,
            response_obj=_pb2.SiteCreateRes,
            method=method,
            **kwargs,
        )

    def SiteUpdate(
        self,
        *,
        request: _pb2.SiteUpdateReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.Result:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/SiteUpdate",
            ctx=ctx,
            request=request,
            response_obj=_pb2.Result,
            method=method,
            **kwargs,
        )

    def SiteDelete(
        self,
        *,
        request: _pb2.ResDeleteReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.Result:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/SiteDelete",
            ctx=ctx,
            request=request,
            response_obj=_pb2.Result,
            method=method,
            **kwargs,
        )

    def SiteImport(
        self,
        *,
        request: _pb2.SiteImportReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.Result:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/SiteImport",
            ctx=ctx,
            request=request,
            response_obj=_pb2.Result,
            method=method,
            **kwargs,
        )

    def SiteSetupCftunnel(
        self,
        *,
        request: _pb2.SiteSetupCftunnelReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.SiteSetupCftunnelReply:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/SiteSetupCftunnel",
            ctx=ctx,
            request=request,
            response_obj=_pb2.SiteSetupCftunnelReply,
            method=method,
            **kwargs,
        )

    def SiteHostList(
        self,
        *,
        request: _pb2.SiteHostListReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.SiteHostListReply:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/SiteHostList",
            ctx=ctx,
            request=request,
            response_obj=_pb2.SiteHostListReply,
            method=method,
            **kwargs,
        )

    def SiteHostGet(
        self,
        *,
        request: _pb2.SiteHostGetReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.SiteHost:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/SiteHostGet",
            ctx=ctx,
            request=request,
            response_obj=_pb2.SiteHost,
            method=method,
            **kwargs,
        )

    def SiteHostCreate(
        self,
        *,
        request: _pb2.SiteHostCreateReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.Result:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/SiteHostCreate",
            ctx=ctx,
            request=request,
            response_obj=_pb2.Result,
            method=method,
            **kwargs,
        )

    def SiteHostUpdate(
        self,
        *,
        request: _pb2.SiteHostUpdateReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.Result:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/SiteHostUpdate",
            ctx=ctx,
            request=request,
            response_obj=_pb2.Result,
            method=method,
            **kwargs,
        )

    def SiteHostDelete(
        self,
        *,
        request: _pb2.ResDeleteReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.Result:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/SiteHostDelete",
            ctx=ctx,
            request=request,
            response_obj=_pb2.Result,
            method=method,
            **kwargs,
        )

    def FormGet(
        self,
        *,
        request: _pb2.FormGetReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.FormSchema:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/FormGet",
            ctx=ctx,
            request=request,
            response_obj=_pb2.FormSchema,
            method=method,
            **kwargs,
        )

    def FormCreate(
        self,
        *,
        request: _pb2.FormCreateReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.FormSchema:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/FormCreate",
            ctx=ctx,
            request=request,
            response_obj=_pb2.FormSchema,
            method=method,
            **kwargs,
        )

    def ArtContentClassify(
        self,
        *,
        request: _pb2.ArtContentClassifyReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.ArtContentClassifyReply:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/ArtContentClassify",
            ctx=ctx,
            request=request,
            response_obj=_pb2.ArtContentClassifyReply,
            method=method,
            **kwargs,
        )

    def ArtRewrite(
        self,
        *,
        request: _pb2.ArtRewriteReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.ArtRewriteReply:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/ArtRewrite",
            ctx=ctx,
            request=request,
            response_obj=_pb2.ArtRewriteReply,
            method=method,
            **kwargs,
        )


class AsyncMtmServiceClient(AsyncConnecpyClient):
    async def Oauth2LoginHook(
        self,
        *,
        request: _pb2.Oauth2LoginHookRequest,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.AuthToken:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/Oauth2LoginHook",
            ctx=ctx,
            request=request,
            response_obj=_pb2.AuthToken,
            method=method,
            session=session,
            **kwargs,
        )

    async def Login(
        self,
        *,
        request: _pb2.LoginReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.LoginReply:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/Login",
            ctx=ctx,
            request=request,
            response_obj=_pb2.LoginReply,
            method=method,
            session=session,
            **kwargs,
        )

    async def Register(
        self,
        *,
        request: _pb2.RegisterReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.RegisterReply:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/Register",
            ctx=ctx,
            request=request,
            response_obj=_pb2.RegisterReply,
            method=method,
            session=session,
            **kwargs,
        )

    async def GetMeta(
        self,
        *,
        request: _pb2.GetMetaReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.GetMetaRes:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/GetMeta",
            ctx=ctx,
            request=request,
            response_obj=_pb2.GetMetaRes,
            method=method,
            session=session,
            **kwargs,
        )

    async def PullLogs(
        self,
        *,
        request: _pb2.PullLogReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.PullLogRes:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/PullLogs",
            ctx=ctx,
            request=request,
            response_obj=_pb2.PullLogRes,
            method=method,
            session=session,
            **kwargs,
        )

    async def MtmServerList(
        self,
        *,
        request: _pb2.MtmServerListReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.MtmServerListRes:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/MtmServerList",
            ctx=ctx,
            request=request,
            response_obj=_pb2.MtmServerListRes,
            method=method,
            session=session,
            **kwargs,
        )

    async def ServiceMeta(
        self,
        *,
        request: _pb2.ServiceMetaReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.ServiceMetaRes:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/ServiceMeta",
            ctx=ctx,
            request=request,
            response_obj=_pb2.ServiceMetaRes,
            method=method,
            session=session,
            **kwargs,
        )

    async def SlugPage(
        self,
        *,
        request: _pb2.SlugReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.SlugRes:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/SlugPage",
            ctx=ctx,
            request=request,
            response_obj=_pb2.SlugRes,
            method=method,
            session=session,
            **kwargs,
        )

    async def Userinfo(
        self,
        *,
        request: _pb2.Empty,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.UserinfoRes:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/Userinfo",
            ctx=ctx,
            request=request,
            response_obj=_pb2.UserinfoRes,
            method=method,
            session=session,
            **kwargs,
        )

    async def BlogPostGet(
        self,
        *,
        request: _pb2.BlogPostGetReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.BlogPost:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/BlogPostGet",
            ctx=ctx,
            request=request,
            response_obj=_pb2.BlogPost,
            method=method,
            session=session,
            **kwargs,
        )

    async def BlogPostCreate(
        self,
        *,
        request: _pb2.BlogPostCreateReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.Result:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/BlogPostCreate",
            ctx=ctx,
            request=request,
            response_obj=_pb2.Result,
            method=method,
            session=session,
            **kwargs,
        )

    async def BlogPostUpdate(
        self,
        *,
        request: _pb2.BlogPostUpdateReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.Result:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/BlogPostUpdate",
            ctx=ctx,
            request=request,
            response_obj=_pb2.Result,
            method=method,
            session=session,
            **kwargs,
        )

    async def BlogPostDelete(
        self,
        *,
        request: _pb2.ResDeleteReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.Result:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/BlogPostDelete",
            ctx=ctx,
            request=request,
            response_obj=_pb2.Result,
            method=method,
            session=session,
            **kwargs,
        )

    async def BlogPostImport(
        self,
        *,
        request: _pb2.BlogPostImportReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.BlogPost:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/BlogPostImport",
            ctx=ctx,
            request=request,
            response_obj=_pb2.BlogPost,
            method=method,
            session=session,
            **kwargs,
        )

    async def BlogCategorieList(
        self,
        *,
        request: _pb2.BlogCategorieListReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.BlogCategorieListReply:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/BlogCategorieList",
            ctx=ctx,
            request=request,
            response_obj=_pb2.BlogCategorieListReply,
            method=method,
            session=session,
            **kwargs,
        )

    async def BlogCategorieGet(
        self,
        *,
        request: _pb2.BlogCategorieGetReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.BlogCategorie:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/BlogCategorieGet",
            ctx=ctx,
            request=request,
            response_obj=_pb2.BlogCategorie,
            method=method,
            session=session,
            **kwargs,
        )

    async def BlogCategorieCreate(
        self,
        *,
        request: _pb2.BlogCategorieCreateReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.BlogCategorieCreateReply:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/BlogCategorieCreate",
            ctx=ctx,
            request=request,
            response_obj=_pb2.BlogCategorieCreateReply,
            method=method,
            session=session,
            **kwargs,
        )

    async def BlogCategorieUpdate(
        self,
        *,
        request: _pb2.BlogCategorieUpdateReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.BlogCategorieUpdateReqply:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/BlogCategorieUpdate",
            ctx=ctx,
            request=request,
            response_obj=_pb2.BlogCategorieUpdateReqply,
            method=method,
            session=session,
            **kwargs,
        )

    async def BlogCategorieDelete(
        self,
        *,
        request: _pb2.ResDeleteReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.Result:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/BlogCategorieDelete",
            ctx=ctx,
            request=request,
            response_obj=_pb2.Result,
            method=method,
            session=session,
            **kwargs,
        )

    async def BlogClean(
        self,
        *,
        request: _pb2.BlogCleanReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.Result:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/BlogClean",
            ctx=ctx,
            request=request,
            response_obj=_pb2.Result,
            method=method,
            session=session,
            **kwargs,
        )

    async def SiteGet(
        self,
        *,
        request: _pb2.SiteGetReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.Site:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/SiteGet",
            ctx=ctx,
            request=request,
            response_obj=_pb2.Site,
            method=method,
            session=session,
            **kwargs,
        )

    async def SiteCreate(
        self,
        *,
        request: _pb2.SiteCreateReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.SiteCreateRes:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/SiteCreate",
            ctx=ctx,
            request=request,
            response_obj=_pb2.SiteCreateRes,
            method=method,
            session=session,
            **kwargs,
        )

    async def SiteUpdate(
        self,
        *,
        request: _pb2.SiteUpdateReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.Result:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/SiteUpdate",
            ctx=ctx,
            request=request,
            response_obj=_pb2.Result,
            method=method,
            session=session,
            **kwargs,
        )

    async def SiteDelete(
        self,
        *,
        request: _pb2.ResDeleteReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.Result:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/SiteDelete",
            ctx=ctx,
            request=request,
            response_obj=_pb2.Result,
            method=method,
            session=session,
            **kwargs,
        )

    async def SiteImport(
        self,
        *,
        request: _pb2.SiteImportReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.Result:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/SiteImport",
            ctx=ctx,
            request=request,
            response_obj=_pb2.Result,
            method=method,
            session=session,
            **kwargs,
        )

    async def SiteSetupCftunnel(
        self,
        *,
        request: _pb2.SiteSetupCftunnelReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.SiteSetupCftunnelReply:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/SiteSetupCftunnel",
            ctx=ctx,
            request=request,
            response_obj=_pb2.SiteSetupCftunnelReply,
            method=method,
            session=session,
            **kwargs,
        )

    async def SiteHostList(
        self,
        *,
        request: _pb2.SiteHostListReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.SiteHostListReply:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/SiteHostList",
            ctx=ctx,
            request=request,
            response_obj=_pb2.SiteHostListReply,
            method=method,
            session=session,
            **kwargs,
        )

    async def SiteHostGet(
        self,
        *,
        request: _pb2.SiteHostGetReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.SiteHost:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/SiteHostGet",
            ctx=ctx,
            request=request,
            response_obj=_pb2.SiteHost,
            method=method,
            session=session,
            **kwargs,
        )

    async def SiteHostCreate(
        self,
        *,
        request: _pb2.SiteHostCreateReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.Result:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/SiteHostCreate",
            ctx=ctx,
            request=request,
            response_obj=_pb2.Result,
            method=method,
            session=session,
            **kwargs,
        )

    async def SiteHostUpdate(
        self,
        *,
        request: _pb2.SiteHostUpdateReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.Result:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/SiteHostUpdate",
            ctx=ctx,
            request=request,
            response_obj=_pb2.Result,
            method=method,
            session=session,
            **kwargs,
        )

    async def SiteHostDelete(
        self,
        *,
        request: _pb2.ResDeleteReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.Result:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/SiteHostDelete",
            ctx=ctx,
            request=request,
            response_obj=_pb2.Result,
            method=method,
            session=session,
            **kwargs,
        )

    async def FormGet(
        self,
        *,
        request: _pb2.FormGetReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.FormSchema:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/FormGet",
            ctx=ctx,
            request=request,
            response_obj=_pb2.FormSchema,
            method=method,
            session=session,
            **kwargs,
        )

    async def FormCreate(
        self,
        *,
        request: _pb2.FormCreateReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.FormSchema:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/FormCreate",
            ctx=ctx,
            request=request,
            response_obj=_pb2.FormSchema,
            method=method,
            session=session,
            **kwargs,
        )

    async def ArtContentClassify(
        self,
        *,
        request: _pb2.ArtContentClassifyReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.ArtContentClassifyReply:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/ArtContentClassify",
            ctx=ctx,
            request=request,
            response_obj=_pb2.ArtContentClassifyReply,
            method=method,
            session=session,
            **kwargs,
        )

    async def ArtRewrite(
        self,
        *,
        request: _pb2.ArtRewriteReq,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.ArtRewriteReply:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtmpb.MtmService/ArtRewrite",
            ctx=ctx,
            request=request,
            response_obj=_pb2.ArtRewriteReply,
            method=method,
            session=session,
            **kwargs,
        )
