# Generated by Django 4.2.9 on 2024-01-14 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lesrooster", "0014_remove_breakslot_period_after"),
    ]

    operations = ([
        migrations.AlterModelManagers(
            name="lesson",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="substitution",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="supervision",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="supervisionsubstitution",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="timeboundcourseconfig",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="timegrid",
            managers=[],
        ),
    ] + [
        migrations.RunSQL(
            f"ALTER TABLE lesrooster_{model_name} drop column if exists site_id;"
        ) for model_name  in
        [
            "lesson",
            "slot",
            "substitution",
            "supervision",
            "supervisionsubstitution",
            "timeboundcourseconfig",
            "timegrid",
            "validityrange"
        ]
    ])
