# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from mtmai.mtmpb import ag_pb2 as mtmai_dot_mtmpb_dot_ag__pb2


class AgServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Greet = channel.stream_unary(
                '/mtmai.mtmpb.AgService/Greet',
                request_serializer=mtmai_dot_mtmpb_dot_ag__pb2.GreetRequest.SerializeToString,
                response_deserializer=mtmai_dot_mtmpb_dot_ag__pb2.GreetResponse.FromString,
                _registered_method=True)
        self.Greet2 = channel.unary_stream(
                '/mtmai.mtmpb.AgService/Greet2',
                request_serializer=mtmai_dot_mtmpb_dot_ag__pb2.GreetRequest.SerializeToString,
                response_deserializer=mtmai_dot_mtmpb_dot_ag__pb2.GreetResponse.FromString,
                _registered_method=True)
        self.ComponentList = channel.unary_unary(
                '/mtmai.mtmpb.AgService/ComponentList',
                request_serializer=mtmai_dot_mtmpb_dot_ag__pb2.ComponentListReq.SerializeToString,
                response_deserializer=mtmai_dot_mtmpb_dot_ag__pb2.ComponentListRes.FromString,
                _registered_method=True)
        self.GetComponent = channel.unary_unary(
                '/mtmai.mtmpb.AgService/GetComponent',
                request_serializer=mtmai_dot_mtmpb_dot_ag__pb2.GetComponentReq.SerializeToString,
                response_deserializer=mtmai_dot_mtmpb_dot_ag__pb2.Component.FromString,
                _registered_method=True)
        self.ListChatMessage = channel.unary_unary(
                '/mtmai.mtmpb.AgService/ListChatMessage',
                request_serializer=mtmai_dot_mtmpb_dot_ag__pb2.ChatMessageListReq.SerializeToString,
                response_deserializer=mtmai_dot_mtmpb_dot_ag__pb2.ChatMessageList.FromString,
                _registered_method=True)
        self.UpsertChat = channel.unary_unary(
                '/mtmai.mtmpb.AgService/UpsertChat',
                request_serializer=mtmai_dot_mtmpb_dot_ag__pb2.UpsertChatReq.SerializeToString,
                response_deserializer=mtmai_dot_mtmpb_dot_ag__pb2.Chat.FromString,
                _registered_method=True)
        self.UpsertChatMessage = channel.unary_unary(
                '/mtmai.mtmpb.AgService/UpsertChatMessage',
                request_serializer=mtmai_dot_mtmpb_dot_ag__pb2.ChatMessageCreateReq.SerializeToString,
                response_deserializer=mtmai_dot_mtmpb_dot_ag__pb2.ChatMessage.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/mtmai.mtmpb.AgService/GetState',
                request_serializer=mtmai_dot_mtmpb_dot_ag__pb2.GetStateReq.SerializeToString,
                response_deserializer=mtmai_dot_mtmpb_dot_ag__pb2.AgState.FromString,
                _registered_method=True)
        self.SetState = channel.unary_unary(
                '/mtmai.mtmpb.AgService/SetState',
                request_serializer=mtmai_dot_mtmpb_dot_ag__pb2.AgState.SerializeToString,
                response_deserializer=mtmai_dot_mtmpb_dot_ag__pb2.AgState.FromString,
                _registered_method=True)


class AgServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Greet(self, request_iterator, context):
        """demos
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Greet2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComponentList(self, request, context):
        """component
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetComponent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChatMessage(self, request, context):
        """chat messages
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertChatMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Greet': grpc.stream_unary_rpc_method_handler(
                    servicer.Greet,
                    request_deserializer=mtmai_dot_mtmpb_dot_ag__pb2.GreetRequest.FromString,
                    response_serializer=mtmai_dot_mtmpb_dot_ag__pb2.GreetResponse.SerializeToString,
            ),
            'Greet2': grpc.unary_stream_rpc_method_handler(
                    servicer.Greet2,
                    request_deserializer=mtmai_dot_mtmpb_dot_ag__pb2.GreetRequest.FromString,
                    response_serializer=mtmai_dot_mtmpb_dot_ag__pb2.GreetResponse.SerializeToString,
            ),
            'ComponentList': grpc.unary_unary_rpc_method_handler(
                    servicer.ComponentList,
                    request_deserializer=mtmai_dot_mtmpb_dot_ag__pb2.ComponentListReq.FromString,
                    response_serializer=mtmai_dot_mtmpb_dot_ag__pb2.ComponentListRes.SerializeToString,
            ),
            'GetComponent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetComponent,
                    request_deserializer=mtmai_dot_mtmpb_dot_ag__pb2.GetComponentReq.FromString,
                    response_serializer=mtmai_dot_mtmpb_dot_ag__pb2.Component.SerializeToString,
            ),
            'ListChatMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChatMessage,
                    request_deserializer=mtmai_dot_mtmpb_dot_ag__pb2.ChatMessageListReq.FromString,
                    response_serializer=mtmai_dot_mtmpb_dot_ag__pb2.ChatMessageList.SerializeToString,
            ),
            'UpsertChat': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertChat,
                    request_deserializer=mtmai_dot_mtmpb_dot_ag__pb2.UpsertChatReq.FromString,
                    response_serializer=mtmai_dot_mtmpb_dot_ag__pb2.Chat.SerializeToString,
            ),
            'UpsertChatMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertChatMessage,
                    request_deserializer=mtmai_dot_mtmpb_dot_ag__pb2.ChatMessageCreateReq.FromString,
                    response_serializer=mtmai_dot_mtmpb_dot_ag__pb2.ChatMessage.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=mtmai_dot_mtmpb_dot_ag__pb2.GetStateReq.FromString,
                    response_serializer=mtmai_dot_mtmpb_dot_ag__pb2.AgState.SerializeToString,
            ),
            'SetState': grpc.unary_unary_rpc_method_handler(
                    servicer.SetState,
                    request_deserializer=mtmai_dot_mtmpb_dot_ag__pb2.AgState.FromString,
                    response_serializer=mtmai_dot_mtmpb_dot_ag__pb2.AgState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mtmai.mtmpb.AgService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mtmai.mtmpb.AgService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Greet(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/mtmai.mtmpb.AgService/Greet',
            mtmai_dot_mtmpb_dot_ag__pb2.GreetRequest.SerializeToString,
            mtmai_dot_mtmpb_dot_ag__pb2.GreetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Greet2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mtmai.mtmpb.AgService/Greet2',
            mtmai_dot_mtmpb_dot_ag__pb2.GreetRequest.SerializeToString,
            mtmai_dot_mtmpb_dot_ag__pb2.GreetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComponentList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtmai.mtmpb.AgService/ComponentList',
            mtmai_dot_mtmpb_dot_ag__pb2.ComponentListReq.SerializeToString,
            mtmai_dot_mtmpb_dot_ag__pb2.ComponentListRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetComponent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtmai.mtmpb.AgService/GetComponent',
            mtmai_dot_mtmpb_dot_ag__pb2.GetComponentReq.SerializeToString,
            mtmai_dot_mtmpb_dot_ag__pb2.Component.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListChatMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtmai.mtmpb.AgService/ListChatMessage',
            mtmai_dot_mtmpb_dot_ag__pb2.ChatMessageListReq.SerializeToString,
            mtmai_dot_mtmpb_dot_ag__pb2.ChatMessageList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtmai.mtmpb.AgService/UpsertChat',
            mtmai_dot_mtmpb_dot_ag__pb2.UpsertChatReq.SerializeToString,
            mtmai_dot_mtmpb_dot_ag__pb2.Chat.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertChatMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtmai.mtmpb.AgService/UpsertChatMessage',
            mtmai_dot_mtmpb_dot_ag__pb2.ChatMessageCreateReq.SerializeToString,
            mtmai_dot_mtmpb_dot_ag__pb2.ChatMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtmai.mtmpb.AgService/GetState',
            mtmai_dot_mtmpb_dot_ag__pb2.GetStateReq.SerializeToString,
            mtmai_dot_mtmpb_dot_ag__pb2.AgState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtmai.mtmpb.AgService/SetState',
            mtmai_dot_mtmpb_dot_ag__pb2.AgState.SerializeToString,
            mtmai_dot_mtmpb_dot_ag__pb2.AgState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
