# Stanford color palette
# taken from https://identity.stanford.edu/design-elements/color/primary-colors/

full_palette = {'Cardinal red': {'Default': '#8C1515',
                                 'Light': '#B83A4B',
                                 'Dark': '#820000'},
                'Palo Alto': {'Default': '#175E54',
                              'Light': '#2D716F',
                              'Dark': '#014240'},
                'Palo Verde': {'Default': '#279989',
                               'Light': '#59B3A9',
                               'Dark': '#017E7C'},
                'Olive': {'Default': '#8F993E',
                          'Light': '#A6B168',
                          'Dark': '#7A863B'},
                'Bay': {'Default': '#6FA287',
                        'Light': '#8AB8A7',
                        'Dark': '#417865'},
                'Sky': {'Default': '#4298B5',
                        'Light': '#67AFD2',
                        'Dark': '#016895'},
                'Lagunita': {'Default': '#007C92',
                             'Light': '#009AB4',
                             'Dark': '#006B81'},
                'Poppy': {'Default': '#E98300',
                          'Light': '#F9A44A',
                          'Dark': '#D1660F'},
                'Spirited': {'Default': '#E04F39',
                             'Light': '#F4795B',
                             'Dark': '#C74632'},
                'Illuminating': {'Default': '#FEDD5C',
                                 'Light': '#FFE781',
                                 'Dark': '#FEC51D'},
                'Plum': {'Default': '#620059',
                         'Light': '#734675',
                         'Dark': '#350D36'},
                'Brick': {'Default': '#651C32',
                          'Light': '#7F2D48',
                          'Dark': '#42081B'},
                'Archway': {'Default': '#5D4B3C',
                            'Light': '#766253',
                            'Dark': '#2F2424'},
                'Stone': {'Default': '#7F7776',
                          'Light': '#D4D1D1',
                          'Dark': '#544948'},
                'Fog': {'Default': '#DAD7CB',
                        'Light': '#F4F4F4',
                        'Dark': '#B6B1A9'},
                'White': {'Default': '#FFFFFF'},
                'Black': {'Default': '#2E2D29',
                          '100%': '#2E2D29',
                          '90%': '#43423E',
                          '80%': '#585754',
                          '70%': '#6D6C69',
                          '60%': '#767674',
                          '50%': '#979694',
                          '40%': '#ABABA9',
                          '30%': '#C0C0BF',
                          '20%': '#D5D5D4',
                          '10%': '#EAEAEA'},
                'Cool grey': {'Default': '#53565A'},
                }

globals().update({key.replace(' ', '_').lower(): inner_dict['Default']
                  for key, inner_dict in full_palette.items()})
