from cfn_resource_provider_schemas.Arczonalshift.Autoshiftobservernotificationstatus import SCHEMA as Autoshiftobservernotificationstatus
from cfn_resource_provider_schemas.Arczonalshift.Zonalautoshiftconfiguration import SCHEMA as Zonalautoshiftconfiguration
