
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-05-22T05:42:22+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "11a44a9900a9e71d3a5adc12b2caf8a2b5f95f93",
 "version": "2.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
