from typing import Dict, List, Any, Union, Literal
import keyword

def merge_dict_fields(): ...
...


class TypeNode:
	...
	def __init__(self, ellipsis = ...): ...

	def merge(): ...

	def __str__(): ...

	def to_typing(): ...

	def to_ready_typing(): ...

def create_node(value: ...) -> TypeNode: ...

def node_to_typing(node: TypeNode, ellipsis = ...): ...