#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2501-52-gf887c60b"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2501
#define NETGEN_VERSION_TWEAK 52
#define NETGEN_VERSION_HASH "gf887c60b"
#endif // NETGEN_VERSION_HPP_INCLUDED
