# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: weave/datamanagement/synthesize/v1/training.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    "",
    "weave/datamanagement/synthesize/v1/training.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n1weave/datamanagement/synthesize/v1/training.proto\x12"weave.datamanagement.synthesize.v1\x1a\x1cgoogle/protobuf/struct.proto"\xc3\x02\n\x1dStartSynthesizerTrainingEvent\x12%\n\x0esynthesizer_id\x18\x01 \x01(\tR\rsynthesizerId\x12\x1f\n\x0b\x64\x61taset_ids\x18\x02 \x03(\tR\ndatasetIds\x12[\n\x0ftraining_driver\x18\x03 \x01(\x0e\x32\x32.weave.datamanagement.synthesize.v1.TrainingDriverR\x0etrainingDriver\x12<\n\rdriver_config\x18\x04 \x01(\x0b\x32\x17.google.protobuf.StructR\x0c\x64riverConfig\x12?\n\x1coutput_storage_connection_id\x18\x05 \x01(\tR\x19outputStorageConnectionId"\x8d\x02\n\x15TrainingProgressEvent\x12L\n\njob_status\x18\x01 \x01(\x0e\x32-.weave.datamanagement.synthesize.v1.JobStatusR\tjobStatus\x12\x1b\n\tstep_name\x18\x02 \x01(\tR\x08stepName\x12N\n\x0bstep_status\x18\x03 \x01(\x0e\x32-.weave.datamanagement.synthesize.v1.JobStatusR\nstepStatus\x12#\n\rstep_progress\x18\x04 \x01(\x02R\x0cstepProgress\x12\x14\n\x05\x65rror\x18\x05 \x01(\tR\x05\x65rror*\x88\x01\n\x0eTrainingDriver\x12\x1f\n\x1bTRAINING_DRIVER_UNSPECIFIED\x10\x00\x12\x1c\n\x18TRAINING_DRIVER_MOSTLYAI\x10\x01\x12\x17\n\x13TRAINING_DRIVER_SDV\x10\x02\x12\x1e\n\x1aTRAINING_DRIVER_SMARTNOISE\x10\x03*\x88\x01\n\tJobStatus\x12\x1a\n\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x16\n\x12JOB_STATUS_PENDING\x10\x01\x12\x16\n\x12JOB_STATUS_RUNNING\x10\x02\x12\x18\n\x14JOB_STATUS_COMPLETED\x10\x03\x12\x15\n\x11JOB_STATUS_FAILED\x10\x04\x42\xb4\x02\n&com.weave.datamanagement.synthesize.v1B\rTrainingProtoP\x01ZPgithub.com/weave-labs/weave-go/pkg/weave/datamanagement/synthesize/v1;synthesize\xa2\x02\x03WDS\xaa\x02"Weave.Datamanagement.Synthesize.V1\xca\x02"Weave\\Datamanagement\\Synthesize\\V1\xe2\x02.Weave\\Datamanagement\\Synthesize\\V1\\GPBMetadata\xea\x02%Weave::Datamanagement::Synthesize::V1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "weave.datamanagement.synthesize.v1.training_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b'\n&com.weave.datamanagement.synthesize.v1B\rTrainingProtoP\001ZPgithub.com/weave-labs/weave-go/pkg/weave/datamanagement/synthesize/v1;synthesize\242\002\003WDS\252\002"Weave.Datamanagement.Synthesize.V1\312\002"Weave\\Datamanagement\\Synthesize\\V1\342\002.Weave\\Datamanagement\\Synthesize\\V1\\GPBMetadata\352\002%Weave::Datamanagement::Synthesize::V1'
    _globals["_TRAININGDRIVER"]._serialized_start = 718
    _globals["_TRAININGDRIVER"]._serialized_end = 854
    _globals["_JOBSTATUS"]._serialized_start = 857
    _globals["_JOBSTATUS"]._serialized_end = 993
    _globals["_STARTSYNTHESIZERTRAININGEVENT"]._serialized_start = 120
    _globals["_STARTSYNTHESIZERTRAININGEVENT"]._serialized_end = 443
    _globals["_TRAININGPROGRESSEVENT"]._serialized_start = 446
    _globals["_TRAININGPROGRESSEVENT"]._serialized_end = 715
# @@protoc_insertion_point(module_scope)
