# PROFILE = {
#     "c5d717a9": {
#         "udid": "c5d717a9",
#         "newCommandTimeout": 300,
#         "noReset": "false",
#         "deviceName": "Phone",
#         "platformName": "Android",
#         "unicodeKeyboard": True,
#         "resetKeyboard": True,
#         "nativeWebScreenshot": True,
#     },
#     "JUBNU19304106288": {
#         "udid": "JUBNU19304106288",
#         "newCommandTimeout": 300,
#         "noReset": "false",
#         "deviceName": "Phone",
#         "platformName": "Android",
#         "unicodeKeyboard": True,
#         "resetKeyboard": True,
#         "nativeWebScreenshot": True,
#     },
#     "iPhone Se": {
#         "automationName": "XCUITest",
#         "platformName": "iOS",
#         "deviceName": "iPhone Simulator",
#         "platformVersion": "13.5",
#         "newCommandTimeout": "3000",
#         "udid": "688B03F5-53D1-451F-AF46-195364B4304A",
#         # "udid": "66623AF6-6E32-4B48-A4EB-01B9BA22DB7A",
#         "showXcodeLog": "false",
#     },
#     "iPad MINI": {
#         "automationName": "XCUITest",
#         "platformName": "iOS",
#         "deviceName": "iPad",
#         "platformVersion": "13.3.1",
#         "newCommandTimeout": "3000",
#         "udid": "6fc0fed86c97e4ab3a71eebe40e18bff079c1806",
#         "xcodeOrgId": "ZPU6X7ZN8Q",

#         # "updateWDABundleId": "com.romwe.WebDriverAgentRunner",
#         "xcodeSigningId": "iPhone Developer",
#         "showXcodeLog": "false",
#     },
#     "iPad": {
#         "automationName": "XCUITest",
#         "platformName": "iOS",
#         "deviceName": "iPad",
#         "platformVersion": "13.4.1",
#         "newCommandTimeout": "3000",
#         "udid": "00008020-000829EA1AE1002E",
#         # "xcodeOrgId": "ZPU6X7ZN8Q",
#         # "xcodeSigningId": "iPhone Developer",
#         # "updateWDABundleId": "com.romwe.WebDriverAgentRunner",
#         "showXcodeLog": "false",
#         "safariInitialUrl": ""
#     },
#     "iPad Pro": {
#         "automationName": "XCUITest",
#         "platformName": "iOS",
#         "deviceName": "iPad",
#         "platformVersion": "11.0",
#         "newCommandTimeout": "3000",
#         "udid": "72c78b5f65b852ff08b2009095a3aec4592eaa7d",
#         # "xcodeOrgId": "ZPU6X7ZN8Q",
#         # "xcodeSigningId": "iPhone Developer",
#         # "updateWDABundleId": "com.romwe.WebDriverAgentRunner",
#         "showXcodeLog": "false",
#         "safariInitialUrl": ""
#     },
#     "iPad Air": {
#         "automationName": "XCUITest",
#         "platformName": "iOS",
#         "deviceName": "iPad",
#         "platformVersion": "13.4.1",
#         "newCommandTimeout": "3000",
#         "udid": "00008020-001014240C99002E",
#         # "xcodeOrgId": "ZPU6X7ZN8Q",
#         # "xcodeSigningId": "iPhone Developer",
#         # "updateWDABundleId": "com.romwe.WebDriverAgentRunner",
#         "showXcodeLog": "false",
#         "safariInitialUrl": ""
#     },
# }
