
# This file was generated by 'versioneer.py' (0.23.dev0) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-05-21T12:25:46+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c53746c32ca7d7d9ae0c009cc6a2d437bb227bc3",
 "version": "1.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
