from cfn_resource_provider_schemas.Shield.Drtaccess import SCHEMA as Drtaccess
from cfn_resource_provider_schemas.Shield.Proactiveengagement import SCHEMA as Proactiveengagement
from cfn_resource_provider_schemas.Shield.Protection import SCHEMA as Protection
from cfn_resource_provider_schemas.Shield.Protectiongroup import SCHEMA as Protectiongroup
